### ISSUE TITLE
Downloaded many versions, none show up.

### ISSUE THREAD

**Issue by O4OUR** [obs-ai/obs-backgroundremoval#471] opened 2023-10-10 19:16 UTC
**Describe the bug**

No matter what version I download and put in the **C:\Program Files (x86)\obs-studio** folder, there's no background remover in the camera effect filters.

**Expected behavior**

The filter to be there.

**Screenshots**

![image](https://github.com/obs-ai/obs-backgroundremoval/assets/147544668/aedd3483-41e0-40f7-b2ad-6c0cac717a15)

**Log Report**

[2023-10-10 11-47-19.txt](https://github.com/obs-ai/obs-backgroundremoval/files/12861061/2023-10-10.11-47-19.txt)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Chrome
 - Plugin Version: 1.1.6 x64
 - OBS Version: 29.1.3

**Additional context**

I've also used the installer and tried both AppData and Programs

**Comment by royshil** [comment] 2023-10-10 19:48
your log is showing no signs of the `obs-backgroundremoval.dll` file
so i'm thinking it's an installation problem, the file is simply in the wrong folder

**Comment by royshil** [comment] 2023-10-10 19:49
this is what i have 
![image](https://github.com/obs-ai/obs-backgroundremoval/assets/441170/cbaeea3f-5e77-49b6-98cc-a7dbb7216c2e)

**Comment by royshil** [comment] 2023-10-10 19:50
try that (copy all the .dll's) and let us see the logs again.
thanks! 🙏

**Comment by O4OUR** [comment] 2023-10-10 20:04
![image](https://github.com/obs-ai/obs-backgroundremoval/assets/147544668/e84c9336-3cfc-4ca9-8220-62d41a8d11b8)

**Comment by umireon** [comment] 2023-10-10 20:10
The OBS installation must not be in Program Files (x86). It must be in Program Files. (without x86).
This screenshot describes that your OBS installation is broken so that can you uninstall OBS and reinstall OBS?

**Comment by O4OUR** [comment] 2023-10-10 20:14
So a fully working OBS that has allowed me to stream for years, WITH plugins, is considered broken because your plugin won't work in any other installation area?

**Comment by royshil** [comment] 2023-10-10 20:19
@O4OUR The problem is that we're compiling x64 and you're running OBS x86
I would suggest you switch to 64-bit since it has performance gains and other benefits
But at the same time we could also consider building x86 32-bit version of our plugin

**Comment by umireon** [comment] 2023-10-10 20:20
Log says that your OBS is 64-bit and I think the x86 one is just a leftover of old OBS installation.

**Comment by O4OUR** [comment] 2023-10-10 20:24
After opening the file location it does show 2 install folders (C: & D:). You are correct! Let me try putting the files in manually.

**Comment by O4OUR** [comment] 2023-10-10 20:26
Look at that. Thank you for fixing 2 problems. 1, I didn't even know I had!
![image](https://github.com/obs-ai/obs-backgroundremoval/assets/147544668/9c537678-9be4-4909-acaa-cfb26fa4c6c4)

**Comment by umireon** [comment] 2023-10-10 20:29
@O4OUR Congrats! Your problems were solved so can we close this issue as completed?

**Comment by umireon** [comment] 2023-10-10 20:31
@royshil I suppose we cannot build 32-bit version of our plugin because OBS provides no 32-bit compatible libraries.

**Closed** 2023-10-10 20:32 UTC
Labels: bug

**Comment by pcalais** [comment] 2023-11-10 22:39
Mine is obs 64 bit and the option does not show up =/

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/7630216/6086f676-df8e-4726-ad80-877c37fe0f5f)
